### PR TITLE
adding archive note

### PR DESCRIPTION
**Pull request by jamaya2001**
@jjasghar Can you please approve/merge this PR?

### CODE REVIEW

**Comment by jjasghar** [comment]
Looks good!

**Comment by morallito** [comment]
@terc1997 - is this a planned merge? @jjasghar please, wait until the TRIRIGA Assistant team reviews this, and approves. 
@jamaya2001 can you contact us via slack and explain what is this PR about?

**Comment by terc1997** [comment]
> @terc1997 - is this a planned merge? @jjasghar please, wait until the TRIRIGA Assistant team reviews this, and approves. @jamaya2001 can you contact us via slack and explain what is this PR about?

@morallito Since this repository is the open communication with the customer, this repository needs to continue open and maintained.

**Comment by jamaya2001** [comment]
We won't archive this repo. I'm closing the request.

**Pull request closed without merging**
